[package]
name = "rp2040-blink-buzz"
version = "0.1.0"
edition = "2021"  # Definindo a edição do Rust como 2021

[dependencies]
cortex-m = "0.7.6"
embedded-hal = "0.2.6"
panic-halt = "0.2.0"
rp2040-hal = "0.7.0"  # Versão correta do rp2040-hal

[build-dependencies]
cortex-m-rt = "0.7.0"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[package.metadata]
cargo-generate = { template = "https://github.com/rp-rs/rp2040-project-template" }


[[bin]]
name = "blinky"
path = "blink.rs"
