[dependencies]
rp2040-hal = "0.7.0"
rtic = { version = "2.1.2", features = ["cortex-m"] }
rtic-macros = { version = "2.1.2", features = ["cortex-m"] }
panic-halt = "0.2.0"
embedded-hal = { version = "0.2.5", features = ["unproven"] }
cortex-m = "0.7.2"
cortex-m-rt = "0.7"
rp2040-boot2 = "0.2.1"
embedded-time = "0.12.1"
defmt = { version = "0.3.10" }
